import React from 'react';

export const gameItems = [
    {id: '001', name: 'Bronze Wire', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'A flexible wire used in various crafting recipes.'},
    {id: '002', name: 'Bronze Chain', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'A series of linked metal rings, used in armor and jewelry.'},
    {id: '003', name: 'Sand Flux', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'A material used to purify metals during smelting.'},
    {id: '004', name: 'Iron Wire', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'A strong, durable wire used in construction and crafting.'},
    {id: '005', name: 'Iron Chain', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'Heavier and stronger than bronze, used for heavy-duty applications.'},
    {id: '006', name: 'Coarse Sandpaper', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'Abrasive paper used for smoothing rough surfaces.'},
    {id: '007', name: 'Tannin', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'A substance used in leather processing to make it durable.'},
    {id: '008', name: 'Coarse Thread', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'A thick thread used in crafting and garment repair.'},
    {id: '009', name: 'Weak Solvent', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'Used to dissolve substances and clean materials.'},
    {id: '010', name: 'Limestone Flux', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'Used in the smelting process to create purer metal ingots.'},
    {id: '011', name: 'Steel Wire', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'A versatile wire used in various applications, from fencing to jewelry.'},
    {id: '012', name: 'Steel Chain', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'Used for lifting heavy items and as a component in machinery.'},
    {id: '013', name: 'Rugged Sandpaper', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'More abrasive than coarse, used for initial stages of sanding.'},
    {id: '014', name: 'Rested Tannin', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'A higher-quality tannin for premium leather goods.'},
    {id: '015', name: 'Fine Thread', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'Used in sewing and embroidery for finer details.'},
    {id: '016', name: 'Potent Solvent', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'A powerful chemical used to break down stubborn materials.'},
    {id: '017', name: 'Liquid Flux', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'Used in high temperature metal joining processes like soldering.'},
    {id: '018', name: 'Silver Wire', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'A precious metal wire used in jewelry making and fine crafts.'},
    {id: '019', name: 'Silver Chain', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'A decorative chain used in jewelry and adornments.'},
    {id: '020', name: 'Fine Sandpaper', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description: 'Used for final smoothing and finishing touches on wood and metal.'},
    {id: '021', name: 'Aged Tannin', rarity: 'Common', level: 12, tier: 3, source: 'Crafting', description: 'Aged for better quality, it is used to produce superior leather items.'},
    {id: '022', name: 'Silken Thread', rarity: 'Common', level: 13, tier: 3, source: 'Crafting', description: 'A high-quality thread for crafting fine garments and textiles.'},
    {id: '023', name: 'Pure Solvent', rarity: 'Common', level: 14, tier: 3, source: 'Crafting', description: 'A highly refined solvent, used in the crafting of delicate items and potions.'},
    {id: '024', name: 'Flint', rarity: 'Common', level: 2, tier: 1, source: 'Gathering', description: 'Commonly used for starting fires and basic toolmaking.'},
    {id: '025', name: 'Fiber', rarity: 'Common', level: 3, tier: 1, source: 'Gathering', description: 'Basic material for making cloth and other textile products.'},
    {id: '026', name: 'Cotton', rarity: 'Common', level: 4, tier: 1, source: 'Gathering', description: 'Soft, natural fiber used in the creation of comfortable clothing.'},
    {id: '027', name: 'Silverleaf', rarity: 'Common', level: 17, tier: 4, source: 'Gathering', description: 'A mystical leaf used in alchemy, known for its healing properties.'},
    {id: '028', name: 'Hemp', rarity: 'Common', level: 5, tier: 1, source: 'Gathering', description: 'A strong, versatile plant used in making ropes and durable textiles.'},
    {id: '029', name: 'Deadleaf', rarity: 'Common', level: 6, tier: 1, source: 'Gathering', description: 'Often used in low-level alchemy and composting.'},
    {id: '030', name: 'Petrified Root', rarity: 'Common', level: 7, tier: 1, source: 'Gathering', description: 'An ancient root with magical qualities, used in crafting and alchemy.'},
    {id: '031', name: 'Silkweed', rarity: 'Common', level: 13, tier: 3, source: 'Gathering', description: 'Used to produce silk, a valuable material for high-tier textiles.'},
    {id: '032', name: 'Frostleaf', rarity: 'Common', level: 8, tier: 1, source: 'Gathering', description: 'A leaf that remains frost-covered, used in cold-resistance potions.'},
    {id: '033', name: 'Beech Log', rarity: 'Common', level: 9, tier: 1, source: 'Logging', description: 'A versatile wood used in building and crafting.'},
    {id: '034', name: 'Beech Tree Sap', rarity: 'Common', level: 10, tier: 1, source: 'Gathering', description: 'Sticky sap used in alchemy and as a natural adhesive.'},
    {id: '035', name: 'Pine Log', rarity: 'Common', level: 11, tier: 1, source: 'Logging', description: 'Commonly used in construction and crafting for its aromatic properties.'},
    {id: '036', name: 'Pine Branch', rarity: 'Common', level: 12, tier: 1, source: 'Logging', description: 'Used in crafting and decoration, known for its pleasant scent.'},
    {id: '037', name: 'Pine Tree Sap', rarity: 'Common', level: 13, tier: 1, source: 'Gathering', description: 'Extracted for use in varnishes and waterproofing materials.'},
    {id: '038', name: 'Oak Log', rarity: 'Common', level: 14, tier: 1, source: 'Logging', description: 'A strong, durable wood used in high-quality furniture and building.'},
    {id: '039', name: 'Oak Branch', rarity: 'Common', level: 15, tier: 1, source: 'Logging', description: 'Sturdy and reliable, used in crafting and construction.'},
    {id: '040', name: 'Oak Tree Sap', rarity: 'Common', level: 16, tier: 1, source: 'Gathering', description: 'A sticky substance used in alchemy and natural remedies.'},
    {id: '041', name: 'Birch Log', rarity: 'Common', level: 17, tier: 1, source: 'Logging', description: 'Valued for its fine grain and versatility in furniture making.'},
    {id: '042', name: 'Birch Branch', rarity: 'Common', level: 18, tier: 1, source: 'Logging', description: 'Often used in decorative crafts and smaller wooden items.'},
    {id: '043', name: 'Birch Tree Sap', rarity: 'Common', level: 19, tier: 1, source: 'Gathering', description: 'Collected for its medicinal properties and as a sweetener.'},
    {id: '044', name: 'Elfwood', rarity: 'Rare', level: 20, tier: 4, source: 'Gathering', description: 'Mystical wood known for its use in elven crafting and magic.'},
    {id: '045', name: 'Emerald Ore', rarity: 'Uncommon', level: 21, tier: 3, source: 'Mining', description: 'Precious ore used for gem cutting and ornamental crafts.'},
    {id: '046', name: 'Copper Ore', rarity: 'Common', level: 5, tier: 1, source: 'Mining', description: 'A ductile metal with very high thermal and electrical conductivity.'},
    {id: '047', name: 'Iron Ore', rarity: 'Common', level: 6, tier: 1, source: 'Mining', description: 'A common metal used in the crafting of various tools and building structures.'},
    {id: '048', name: 'Coal', rarity: 'Common', level: 7, tier: 1, source: 'Mining', description: 'Crucial for fueling furnaces and forges in crafting and smelting processes.'},
    {id: '049', name: 'Brilliant Ruby Ore', rarity: 'Uncommon', level: 22, tier: 3, source: 'Mining', description: 'Rare ore that can be polished into valuable jewelry and enchantments.'},
    {id: '050', name: 'Amber Ore', rarity: 'Uncommon', level: 23, tier: 3, source: 'Mining', description: 'Fossilized resin used in jewelry and for its supposed mystical properties.'},
    {id: '051', name: 'Silver Ore', rarity: 'Uncommon', level: 24, tier: 4, source: 'Mining', description: 'A soft, white, lustrous metal used in high-quality crafts and silverware.'},
    {id: '052', name: 'Celestine Ore', rarity: 'Rare', level: 25, tier: 4, source: 'Mining', description: 'An heavenly ore used in crafting artifacts of immense power.'},
    {id: '053', name: 'Brilliant Aquamarine Ore', rarity: 'Uncommon', level: 26, tier: 4, source: 'Mining', description: 'Beautiful sea-blue gem used in high-tier jewelry and magical artifacts.'},
    {id: '054', name: 'Pristine Crystal Ore', rarity: 'Rare', level: 27, tier: 4, source: 'Mining', description: 'Exceptionally pure crystal, sought after for its magical properties.'},
    {id: '055', name: 'Rawhide', rarity: 'Common', level: 8, tier: 1, source: 'Gathering', description: 'Untreated hide from animals, used in basic leather crafting.'},
    {id: '056', name: 'Light Hide', rarity: 'Common', level: 9, tier: 1, source: 'Gathering', description: 'Lighter and more flexible than rawhide, used for mid-tier leather goods.'},
    {id: '057', name: 'Fox Pelt', rarity: 'Common', level: 10, tier: 1, source: 'Gathering', description: 'Soft and warm, ideal for clothing and upholstery.'},
    {id: '058', name: 'Heavy Hide', rarity: 'Common', level: 11, tier: 1, source: 'Gathering', description: 'Thick and durable, used for crafting heavy-duty gear and armor.'},
    {id: '059', name: 'Basilisk Scale', rarity: 'Rare', level: 28, tier: 4, source: 'Hunting', description: 'Legendary scales that are incredibly hard and resistant to magic.'},
    {id: '060', name: 'Rugged Hide', rarity: 'Common', level: 12, tier: 1, source: 'Gathering', description: 'Even tougher than heavy hide, it is used for the toughest of leather products.'},
    {id: '061', name: 'Shimmering Scale', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '062', name: 'Polar Bear Pelt', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '063', name: 'Bronze Ingot', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '064', name: 'Iron Ingot', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '065', name: 'Steel Ingot', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '066', name: 'Silver Ingot', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '067', name: 'Flint Harvesting Sickle', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '068', name: 'Flint Logging Axe', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '069', name: 'Flint Mining Pickaxe', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '070', name: 'Flint Skinning Knife', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '071', name: 'Bronze Harvesting Sickle', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '072', name: 'Bronze Enginnering Hammer', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '073', name: 'Bronze Mining Pickaxe', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '074', name: 'Bronze Tailoring Needle', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '075', name: 'Bronze Logging Axe', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '076', name: 'Bronze Blacksmithing Hammer', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '077', name: 'Bronze Skinning Knife', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '078', name: 'Bronze Leatherworking Knife', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '079', name: 'Bronze Woodworking Saw', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '080', name: 'Iron Nut', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '081', name: 'Iron Woodworking Saw', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '082', name: 'Iron Blacksmithing Hammer', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '083', name: 'Iron Engineering Hammer', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '084', name: 'Iron Harvesting Sickle', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '085', name: 'Iron Mining Pickaxe', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '086', name: 'Iron Tailoring Needle', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '087', name: 'Iron Skinning Knife', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '088', name: 'Iron Leatherworking Knife', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '089', name: 'Iron Logging Axe', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '090', name: 'Steel Nut', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '091', name: 'Steel Leatherworking Knife', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '092', name: 'Steel Mining Pickaxe', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '093', name: 'Steel Tailoring Needle', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '094', name: 'Steel Harvesting Sickle', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '095', name: 'Steel Engineering Hammer', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '096', name: 'Steel Skinning Knife', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '097', name: 'Steel Woodworking Saw', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '098', name: 'Steel Blacksmithing Hammer', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '099', name: 'Steel Logging Axe', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '100', name: 'Silver Nut', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '101', name: 'Silver Skinning Knife', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '102', name: 'Silver Engineering hammer', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '103', name: 'Silver Woodworking Saw', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '104', name: 'Silver Harvesting Sickle', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '105', name: 'Silver Mining Pickaxe', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '106', name: 'Silver Blacksmithing Hammer', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '107', name: 'Silver Leatherworking Knife', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '108', name: 'Silver Tailoring Needle', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '109', name: 'Silver Logging Axe', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '110', name: 'Flint Ring', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '111', name: 'Bronze Ring', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '112', name: 'Bronze Earrings', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '113', name: 'Bronze Necklace', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '114', name: 'Cut Emerald', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '115', name: 'Iron Ring', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '116', name: 'Iron Earrings', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '117', name: 'Iron Necklace', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '118', name: 'Iron Emerald Ring', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '119', name: 'Iron Emerald Earrings', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '120', name: 'Iron Emerald Necklace', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '121', name: 'Cut Amber', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '122', name: 'Cut Brilliant Ruby', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '123', name: 'Steel Ring', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '124', name: 'Steel Earrings', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '125', name: 'Steel Necklace', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '126', name: 'Steel Amber Ring', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '127', name: 'Steel Amber Earrings', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '128', name: 'Steel Amber Necklace', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '129', name: 'Steel Brilliant RubyRing ', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '130', name: 'Cut Pristine Crystal', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '131', name: 'Cut Brilliant Aquamarine', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '132', name: 'Cut Celestine Silver Ring', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '133', name: 'Silver Earrings', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '134', name: 'Silver Necklace ', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '135', name: 'Silver Celestine Ring', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '136', name: 'Silver Celestine Necklace', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '137', name: 'Silver Celestine Earrings', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '138', name: 'Silver Brilliant Aquamarine Ring', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '139', name: 'Silver Pristine Crystal Earrings', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '140', name: 'Coarse Leather', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '141', name: 'Coarse Leather Boots', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '142', name: 'Coarse Leather', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '143', name: 'Belt Coarse', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '144', name: 'Leather Gloves', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '145', name: 'Coarse Leather Cap ', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '146', name: 'Coarse Leather Apron', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '147', name: 'Light Leather', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '148', name: 'Light Leather Boots', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '149', name: 'Light Leather Belt', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '150', name: 'Light Leather Gloves', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '151', name: 'Light Leather Cap', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '152', name: 'Light Leather Apron', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '153', name: 'Heavy Leather', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '154', name: 'Heavy Leather Boots', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '155', name: 'Heavy Leather Belt', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '156', name: 'Heavy Leather Gloves', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '157', name: 'Heavy Leather Cap', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '158', name: 'Heavy Leather Apron', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '159', name: 'Rugged Leather', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '160', name: 'Rugged Leather Boots', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '161', name: 'Rugged Leather Belt', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '162', name: 'Rugged Leather Gloves', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '163', name: 'Rugged Leather Cap', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '164', name: 'Rugged Leather Apron', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '165', name: 'Linen Cloth ', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '166', name: 'Linen Sash', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '167', name: 'Linen Gloves', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '168', name: 'Linen Bandana', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '169', name: 'Linen Shirt', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '170', name: 'Wool Cloth', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '171', name: 'Woolen Sash', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '172', name: 'Woolen Gloves', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '173', name: 'Woolen Bandana', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '174', name: 'Woolen Shirt ', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '175', name: 'Sateen ', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '176', name: 'Sateen Sash ', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '177', name: 'Sateen Gloves', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '178', name: 'Sateen Bandana', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '179', name: 'Sateen Shirt', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '180', name: 'Silk Cloth', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '181', name: 'Silk Sash', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '182', name: 'Silk Gloves', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '183', name: 'Silk Bandana', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '184', name: 'Silk Shirt', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '185', name: 'Beech Lumber', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '186', name: 'Pine Lumber', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '187', name: 'Oak Lumber', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '188', name: 'Birch Lumber', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '189', name: 'Gold Sack', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '190', name: 'Care Package', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '191', name: 'Announcement', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
    {id: '192', name: 'Server Reset Vote', rarity: 'Common', level: 4, tier: 1, source: 'Crafting', description:'sample-text'},
];
